// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/ics23/v1/proofs.proto

package com.cosmos.ics23.v1;

public interface CompressedNonExistenceProofOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cosmos.ics23.v1.CompressedNonExistenceProof)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * TODO: remove this as unnecessary??? we prove a range
   * </pre>
   *
   * <code>bytes key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>.cosmos.ics23.v1.CompressedExistenceProof left = 2 [json_name = "left"];</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>.cosmos.ics23.v1.CompressedExistenceProof left = 2 [json_name = "left"];</code>
   * @return The left.
   */
  com.cosmos.ics23.v1.CompressedExistenceProof getLeft();

  /**
   * <code>.cosmos.ics23.v1.CompressedExistenceProof right = 3 [json_name = "right"];</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>.cosmos.ics23.v1.CompressedExistenceProof right = 3 [json_name = "right"];</code>
   * @return The right.
   */
  com.cosmos.ics23.v1.CompressedExistenceProof getRight();
}
