// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/ics23/v1/proofs.proto

package com.cosmos.ics23.v1;

public interface LeafOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cosmos.ics23.v1.LeafOp)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.cosmos.ics23.v1.HashOp hash = 1 [json_name = "hash"];</code>
   * @return The enum numeric value on the wire for hash.
   */
  int getHashValue();
  /**
   * <code>.cosmos.ics23.v1.HashOp hash = 1 [json_name = "hash"];</code>
   * @return The hash.
   */
  com.cosmos.ics23.v1.HashOp getHash();

  /**
   * <code>.cosmos.ics23.v1.HashOp prehash_key = 2 [json_name = "prehashKey"];</code>
   * @return The enum numeric value on the wire for prehashKey.
   */
  int getPrehashKeyValue();
  /**
   * <code>.cosmos.ics23.v1.HashOp prehash_key = 2 [json_name = "prehashKey"];</code>
   * @return The prehashKey.
   */
  com.cosmos.ics23.v1.HashOp getPrehashKey();

  /**
   * <code>.cosmos.ics23.v1.HashOp prehash_value = 3 [json_name = "prehashValue"];</code>
   * @return The enum numeric value on the wire for prehashValue.
   */
  int getPrehashValueValue();
  /**
   * <code>.cosmos.ics23.v1.HashOp prehash_value = 3 [json_name = "prehashValue"];</code>
   * @return The prehashValue.
   */
  com.cosmos.ics23.v1.HashOp getPrehashValue();

  /**
   * <code>.cosmos.ics23.v1.LengthOp length = 4 [json_name = "length"];</code>
   * @return The enum numeric value on the wire for length.
   */
  int getLengthValue();
  /**
   * <code>.cosmos.ics23.v1.LengthOp length = 4 [json_name = "length"];</code>
   * @return The length.
   */
  com.cosmos.ics23.v1.LengthOp getLength();

  /**
   * <pre>
   * prefix is a fixed bytes that may optionally be included at the beginning to differentiate
   * a leaf node from an inner node.
   * </pre>
   *
   * <code>bytes prefix = 5 [json_name = "prefix"];</code>
   * @return The prefix.
   */
  com.google.protobuf.ByteString getPrefix();
}
