// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/03-connection/Connection.proto

package com.icon.proto.core.connection;

/**
 * <pre>
 * Version defines the versioning scheme used to negotiate the IBC verison in
 * the connection handshake.
 * </pre>
 *
 * Protobuf type {@code icon.proto.core.connection.Version}
 */
public  final class Version extends
    com.google.protobuf.GeneratedMessageLite<
        Version, Version.Builder> implements
    // @@protoc_insertion_point(message_implements:icon.proto.core.connection.Version)
    VersionOrBuilder {
  private Version() {
    identifier_ = "";
    features_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private java.lang.String identifier_;
  /**
   * <pre>
   * unique version identifier
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @return The identifier.
   */
  @java.lang.Override
  public java.lang.String getIdentifier() {
    return identifier_;
  }
  /**
   * <pre>
   * unique version identifier
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @return The bytes for identifier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdentifierBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(identifier_);
  }
  /**
   * <pre>
   * unique version identifier
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @param value The identifier to set.
   */
  private void setIdentifier(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    identifier_ = value;
  }
  /**
   * <pre>
   * unique version identifier
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   */
  private void clearIdentifier() {
    
    identifier_ = getDefaultInstance().getIdentifier();
  }
  /**
   * <pre>
   * unique version identifier
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @param value The bytes for identifier to set.
   */
  private void setIdentifierBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    identifier_ = value.toStringUtf8();
    
  }

  public static final int FEATURES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> features_;
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @return A list containing the features.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getFeaturesList() {
    return features_;
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @return The count of features.
   */
  @java.lang.Override
  public int getFeaturesCount() {
    return features_.size();
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @param index The index of the element to return.
   * @return The features at the given index.
   */
  @java.lang.Override
  public java.lang.String getFeatures(int index) {
    return features_.get(index);
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the features at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFeaturesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        features_.get(index));
  }
  private void ensureFeaturesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        features_;  if (!tmp.isModifiable()) {
      features_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @param index The index to set the value at.
   * @param value The features to set.
   */
  private void setFeatures(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureFeaturesIsMutable();
    features_.set(index, value);
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @param value The features to add.
   */
  private void addFeatures(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureFeaturesIsMutable();
    features_.add(value);
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @param values The features to add.
   */
  private void addAllFeatures(
      java.lang.Iterable<java.lang.String> values) {
    ensureFeaturesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, features_);
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   */
  private void clearFeatures() {
    features_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * list of features compatible with the specified identifier
   * </pre>
   *
   * <code>repeated string features = 2 [json_name = "features"];</code>
   * @param value The bytes of the features to add.
   */
  private void addFeaturesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureFeaturesIsMutable();
    features_.add(value.toStringUtf8());
  }

  public static com.icon.proto.core.connection.Version parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.icon.proto.core.connection.Version parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.icon.proto.core.connection.Version parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.icon.proto.core.connection.Version parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.icon.proto.core.connection.Version parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.icon.proto.core.connection.Version parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.icon.proto.core.connection.Version prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Version defines the versioning scheme used to negotiate the IBC verison in
   * the connection handshake.
   * </pre>
   *
   * Protobuf type {@code icon.proto.core.connection.Version}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.icon.proto.core.connection.Version, Builder> implements
      // @@protoc_insertion_point(builder_implements:icon.proto.core.connection.Version)
      com.icon.proto.core.connection.VersionOrBuilder {
    // Construct using com.icon.proto.core.connection.Version.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return The identifier.
     */
    @java.lang.Override
    public java.lang.String getIdentifier() {
      return instance.getIdentifier();
    }
    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return The bytes for identifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      return instance.getIdentifierBytes();
    }
    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @param value The identifier to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifier(
        java.lang.String value) {
      copyOnWrite();
      instance.setIdentifier(value);
      return this;
    }
    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentifier() {
      copyOnWrite();
      instance.clearIdentifier();
      return this;
    }
    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1 [json_name = "identifier"];</code>
     * @param value The bytes for identifier to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdentifierBytes(value);
      return this;
    }

    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @return A list containing the features.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getFeaturesList() {
      return java.util.Collections.unmodifiableList(
          instance.getFeaturesList());
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @return The count of features.
     */
    @java.lang.Override
    public int getFeaturesCount() {
      return instance.getFeaturesCount();
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @param index The index of the element to return.
     * @return The features at the given index.
     */
    @java.lang.Override
    public java.lang.String getFeatures(int index) {
      return instance.getFeatures(index);
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the features at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFeaturesBytes(int index) {
      return instance.getFeaturesBytes(index);
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @param index The index to set the value at.
     * @param value The features to set.
     * @return This builder for chaining.
     */
    public Builder setFeatures(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setFeatures(index, value);
      return this;
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @param value The features to add.
     * @return This builder for chaining.
     */
    public Builder addFeatures(
        java.lang.String value) {
      copyOnWrite();
      instance.addFeatures(value);
      return this;
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @param values The features to add.
     * @return This builder for chaining.
     */
    public Builder addAllFeatures(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllFeatures(values);
      return this;
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFeatures() {
      copyOnWrite();
      instance.clearFeatures();
      return this;
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2 [json_name = "features"];</code>
     * @param value The bytes of the features to add.
     * @return This builder for chaining.
     */
    public Builder addFeaturesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addFeaturesBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:icon.proto.core.connection.Version)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.icon.proto.core.connection.Version();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "identifier_",
            "features_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u021a" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.icon.proto.core.connection.Version> parser = PARSER;
        if (parser == null) {
          synchronized (com.icon.proto.core.connection.Version.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.icon.proto.core.connection.Version>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:icon.proto.core.connection.Version)
  private static final com.icon.proto.core.connection.Version DEFAULT_INSTANCE;
  static {
    Version defaultInstance = new Version();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Version.class, defaultInstance);
  }

  public static com.icon.proto.core.connection.Version getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Version> PARSER;

  public static com.google.protobuf.Parser<Version> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

