// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/core/client/v1/client.proto

package com.ibc.core.client.v1;

/**
 * <pre>
 * ClientUpdateProposal is a governance proposal. If it passes, the substitute
 * client's latest consensus state is copied over to the subject client. The proposal
 * handler may fail if the subject and the substitute do not match in client and
 * chain parameters (with exception to latest height, frozen height, and chain-id).
 * </pre>
 *
 * Protobuf type {@code ibc.core.client.v1.ClientUpdateProposal}
 */
public  final class ClientUpdateProposal extends
    com.google.protobuf.GeneratedMessageLite<
        ClientUpdateProposal, ClientUpdateProposal.Builder> implements
    // @@protoc_insertion_point(message_implements:ibc.core.client.v1.ClientUpdateProposal)
    ClientUpdateProposalOrBuilder {
  private ClientUpdateProposal() {
    title_ = "";
    description_ = "";
    subjectClientId_ = "";
    substituteClientId_ = "";
  }
  public static final int TITLE_FIELD_NUMBER = 1;
  private java.lang.String title_;
  /**
   * <pre>
   * the title of the update proposal
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * the title of the update proposal
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * the title of the update proposal
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <pre>
   * the title of the update proposal
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * the title of the update proposal
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();
    
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private java.lang.String description_;
  /**
   * <pre>
   * the description of the proposal
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <pre>
   * the description of the proposal
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <pre>
   * the description of the proposal
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <pre>
   * the description of the proposal
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   */
  private void clearDescription() {
    
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <pre>
   * the description of the proposal
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();
    
  }

  public static final int SUBJECT_CLIENT_ID_FIELD_NUMBER = 3;
  private java.lang.String subjectClientId_;
  /**
   * <pre>
   * the client identifier for the client to be updated if the proposal passes
   * </pre>
   *
   * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
   * @return The subjectClientId.
   */
  @java.lang.Override
  public java.lang.String getSubjectClientId() {
    return subjectClientId_;
  }
  /**
   * <pre>
   * the client identifier for the client to be updated if the proposal passes
   * </pre>
   *
   * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
   * @return The bytes for subjectClientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(subjectClientId_);
  }
  /**
   * <pre>
   * the client identifier for the client to be updated if the proposal passes
   * </pre>
   *
   * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
   * @param value The subjectClientId to set.
   */
  private void setSubjectClientId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    subjectClientId_ = value;
  }
  /**
   * <pre>
   * the client identifier for the client to be updated if the proposal passes
   * </pre>
   *
   * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
   */
  private void clearSubjectClientId() {
    
    subjectClientId_ = getDefaultInstance().getSubjectClientId();
  }
  /**
   * <pre>
   * the client identifier for the client to be updated if the proposal passes
   * </pre>
   *
   * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
   * @param value The bytes for subjectClientId to set.
   */
  private void setSubjectClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    subjectClientId_ = value.toStringUtf8();
    
  }

  public static final int SUBSTITUTE_CLIENT_ID_FIELD_NUMBER = 4;
  private java.lang.String substituteClientId_;
  /**
   * <pre>
   * the substitute client identifier for the client standing in for the subject
   * client
   * </pre>
   *
   * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
   * @return The substituteClientId.
   */
  @java.lang.Override
  public java.lang.String getSubstituteClientId() {
    return substituteClientId_;
  }
  /**
   * <pre>
   * the substitute client identifier for the client standing in for the subject
   * client
   * </pre>
   *
   * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
   * @return The bytes for substituteClientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubstituteClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(substituteClientId_);
  }
  /**
   * <pre>
   * the substitute client identifier for the client standing in for the subject
   * client
   * </pre>
   *
   * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
   * @param value The substituteClientId to set.
   */
  private void setSubstituteClientId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    substituteClientId_ = value;
  }
  /**
   * <pre>
   * the substitute client identifier for the client standing in for the subject
   * client
   * </pre>
   *
   * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
   */
  private void clearSubstituteClientId() {
    
    substituteClientId_ = getDefaultInstance().getSubstituteClientId();
  }
  /**
   * <pre>
   * the substitute client identifier for the client standing in for the subject
   * client
   * </pre>
   *
   * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
   * @param value The bytes for substituteClientId to set.
   */
  private void setSubstituteClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    substituteClientId_ = value.toStringUtf8();
    
  }

  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ibc.core.client.v1.ClientUpdateProposal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ibc.core.client.v1.ClientUpdateProposal prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ClientUpdateProposal is a governance proposal. If it passes, the substitute
   * client's latest consensus state is copied over to the subject client. The proposal
   * handler may fail if the subject and the substitute do not match in client and
   * chain parameters (with exception to latest height, frozen height, and chain-id).
   * </pre>
   *
   * Protobuf type {@code ibc.core.client.v1.ClientUpdateProposal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ibc.core.client.v1.ClientUpdateProposal, Builder> implements
      // @@protoc_insertion_point(builder_implements:ibc.core.client.v1.ClientUpdateProposal)
      com.ibc.core.client.v1.ClientUpdateProposalOrBuilder {
    // Construct using com.ibc.core.client.v1.ClientUpdateProposal.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <pre>
     * the client identifier for the client to be updated if the proposal passes
     * </pre>
     *
     * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
     * @return The subjectClientId.
     */
    @java.lang.Override
    public java.lang.String getSubjectClientId() {
      return instance.getSubjectClientId();
    }
    /**
     * <pre>
     * the client identifier for the client to be updated if the proposal passes
     * </pre>
     *
     * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
     * @return The bytes for subjectClientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubjectClientIdBytes() {
      return instance.getSubjectClientIdBytes();
    }
    /**
     * <pre>
     * the client identifier for the client to be updated if the proposal passes
     * </pre>
     *
     * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
     * @param value The subjectClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSubjectClientId(value);
      return this;
    }
    /**
     * <pre>
     * the client identifier for the client to be updated if the proposal passes
     * </pre>
     *
     * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjectClientId() {
      copyOnWrite();
      instance.clearSubjectClientId();
      return this;
    }
    /**
     * <pre>
     * the client identifier for the client to be updated if the proposal passes
     * </pre>
     *
     * <code>string subject_client_id = 3 [json_name = "subjectClientId"];</code>
     * @param value The bytes for subjectClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSubjectClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * the substitute client identifier for the client standing in for the subject
     * client
     * </pre>
     *
     * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
     * @return The substituteClientId.
     */
    @java.lang.Override
    public java.lang.String getSubstituteClientId() {
      return instance.getSubstituteClientId();
    }
    /**
     * <pre>
     * the substitute client identifier for the client standing in for the subject
     * client
     * </pre>
     *
     * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
     * @return The bytes for substituteClientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubstituteClientIdBytes() {
      return instance.getSubstituteClientIdBytes();
    }
    /**
     * <pre>
     * the substitute client identifier for the client standing in for the subject
     * client
     * </pre>
     *
     * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
     * @param value The substituteClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSubstituteClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSubstituteClientId(value);
      return this;
    }
    /**
     * <pre>
     * the substitute client identifier for the client standing in for the subject
     * client
     * </pre>
     *
     * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubstituteClientId() {
      copyOnWrite();
      instance.clearSubstituteClientId();
      return this;
    }
    /**
     * <pre>
     * the substitute client identifier for the client standing in for the subject
     * client
     * </pre>
     *
     * <code>string substitute_client_id = 4 [json_name = "substituteClientId"];</code>
     * @param value The bytes for substituteClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSubstituteClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSubstituteClientIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ibc.core.client.v1.ClientUpdateProposal)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ibc.core.client.v1.ClientUpdateProposal();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "title_",
            "description_",
            "subjectClientId_",
            "substituteClientId_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ibc.core.client.v1.ClientUpdateProposal> parser = PARSER;
        if (parser == null) {
          synchronized (com.ibc.core.client.v1.ClientUpdateProposal.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ibc.core.client.v1.ClientUpdateProposal>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ibc.core.client.v1.ClientUpdateProposal)
  private static final com.ibc.core.client.v1.ClientUpdateProposal DEFAULT_INSTANCE;
  static {
    ClientUpdateProposal defaultInstance = new ClientUpdateProposal();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ClientUpdateProposal.class, defaultInstance);
  }

  public static com.ibc.core.client.v1.ClientUpdateProposal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ClientUpdateProposal> PARSER;

  public static com.google.protobuf.Parser<ClientUpdateProposal> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

