// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/core/client/v1/client.proto

package com.ibc.core.client.v1;

/**
 * <pre>
 * ConsensusStateWithHeight defines a consensus state with an additional height
 * field.
 * </pre>
 *
 * Protobuf type {@code ibc.core.client.v1.ConsensusStateWithHeight}
 */
public  final class ConsensusStateWithHeight extends
    com.google.protobuf.GeneratedMessageLite<
        ConsensusStateWithHeight, ConsensusStateWithHeight.Builder> implements
    // @@protoc_insertion_point(message_implements:ibc.core.client.v1.ConsensusStateWithHeight)
    ConsensusStateWithHeightOrBuilder {
  private ConsensusStateWithHeight() {
  }
  public static final int HEIGHT_FIELD_NUMBER = 1;
  private com.ibc.core.client.v1.Height height_;
  /**
   * <pre>
   * consensus state height
   * </pre>
   *
   * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public boolean hasHeight() {
    return height_ != null;
  }
  /**
   * <pre>
   * consensus state height
   * </pre>
   *
   * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.ibc.core.client.v1.Height getHeight() {
    return height_ == null ? com.ibc.core.client.v1.Height.getDefaultInstance() : height_;
  }
  /**
   * <pre>
   * consensus state height
   * </pre>
   *
   * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
   */
  private void setHeight(com.ibc.core.client.v1.Height value) {
    value.getClass();
  height_ = value;
    
    }
  /**
   * <pre>
   * consensus state height
   * </pre>
   *
   * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeHeight(com.ibc.core.client.v1.Height value) {
    value.getClass();
  if (height_ != null &&
        height_ != com.ibc.core.client.v1.Height.getDefaultInstance()) {
      height_ =
        com.ibc.core.client.v1.Height.newBuilder(height_).mergeFrom(value).buildPartial();
    } else {
      height_ = value;
    }
    
  }
  /**
   * <pre>
   * consensus state height
   * </pre>
   *
   * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
   */
  private void clearHeight() {  height_ = null;
    
  }

  public static final int CONSENSUS_STATE_FIELD_NUMBER = 2;
  private com.google.protobuf.Any consensusState_;
  /**
   * <pre>
   * consensus state
   * </pre>
   *
   * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
   */
  @java.lang.Override
  public boolean hasConsensusState() {
    return consensusState_ != null;
  }
  /**
   * <pre>
   * consensus state
   * </pre>
   *
   * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Any getConsensusState() {
    return consensusState_ == null ? com.google.protobuf.Any.getDefaultInstance() : consensusState_;
  }
  /**
   * <pre>
   * consensus state
   * </pre>
   *
   * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
   */
  private void setConsensusState(com.google.protobuf.Any value) {
    value.getClass();
  consensusState_ = value;
    
    }
  /**
   * <pre>
   * consensus state
   * </pre>
   *
   * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeConsensusState(com.google.protobuf.Any value) {
    value.getClass();
  if (consensusState_ != null &&
        consensusState_ != com.google.protobuf.Any.getDefaultInstance()) {
      consensusState_ =
        com.google.protobuf.Any.newBuilder(consensusState_).mergeFrom(value).buildPartial();
    } else {
      consensusState_ = value;
    }
    
  }
  /**
   * <pre>
   * consensus state
   * </pre>
   *
   * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
   */
  private void clearConsensusState() {  consensusState_ = null;
    
  }

  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ibc.core.client.v1.ConsensusStateWithHeight parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ibc.core.client.v1.ConsensusStateWithHeight prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ConsensusStateWithHeight defines a consensus state with an additional height
   * field.
   * </pre>
   *
   * Protobuf type {@code ibc.core.client.v1.ConsensusStateWithHeight}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ibc.core.client.v1.ConsensusStateWithHeight, Builder> implements
      // @@protoc_insertion_point(builder_implements:ibc.core.client.v1.ConsensusStateWithHeight)
      com.ibc.core.client.v1.ConsensusStateWithHeightOrBuilder {
    // Construct using com.ibc.core.client.v1.ConsensusStateWithHeight.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * consensus state height
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public boolean hasHeight() {
      return instance.hasHeight();
    }
    /**
     * <pre>
     * consensus state height
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public com.ibc.core.client.v1.Height getHeight() {
      return instance.getHeight();
    }
    /**
     * <pre>
     * consensus state height
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
     */
    public Builder setHeight(com.ibc.core.client.v1.Height value) {
      copyOnWrite();
      instance.setHeight(value);
      return this;
      }
    /**
     * <pre>
     * consensus state height
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
     */
    public Builder setHeight(
        com.ibc.core.client.v1.Height.Builder builderForValue) {
      copyOnWrite();
      instance.setHeight(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * consensus state height
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
     */
    public Builder mergeHeight(com.ibc.core.client.v1.Height value) {
      copyOnWrite();
      instance.mergeHeight(value);
      return this;
    }
    /**
     * <pre>
     * consensus state height
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height height = 1 [json_name = "height", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearHeight() {  copyOnWrite();
      instance.clearHeight();
      return this;
    }

    /**
     * <pre>
     * consensus state
     * </pre>
     *
     * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
     */
    @java.lang.Override
    public boolean hasConsensusState() {
      return instance.hasConsensusState();
    }
    /**
     * <pre>
     * consensus state
     * </pre>
     *
     * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getConsensusState() {
      return instance.getConsensusState();
    }
    /**
     * <pre>
     * consensus state
     * </pre>
     *
     * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
     */
    public Builder setConsensusState(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.setConsensusState(value);
      return this;
      }
    /**
     * <pre>
     * consensus state
     * </pre>
     *
     * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
     */
    public Builder setConsensusState(
        com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.setConsensusState(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * consensus state
     * </pre>
     *
     * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
     */
    public Builder mergeConsensusState(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.mergeConsensusState(value);
      return this;
    }
    /**
     * <pre>
     * consensus state
     * </pre>
     *
     * <code>.google.protobuf.Any consensus_state = 2 [json_name = "consensusState"];</code>
     */
    public Builder clearConsensusState() {  copyOnWrite();
      instance.clearConsensusState();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ibc.core.client.v1.ConsensusStateWithHeight)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ibc.core.client.v1.ConsensusStateWithHeight();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "height_",
            "consensusState_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\t\u0002\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ibc.core.client.v1.ConsensusStateWithHeight> parser = PARSER;
        if (parser == null) {
          synchronized (com.ibc.core.client.v1.ConsensusStateWithHeight.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ibc.core.client.v1.ConsensusStateWithHeight>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ibc.core.client.v1.ConsensusStateWithHeight)
  private static final com.ibc.core.client.v1.ConsensusStateWithHeight DEFAULT_INSTANCE;
  static {
    ConsensusStateWithHeight defaultInstance = new ConsensusStateWithHeight();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ConsensusStateWithHeight.class, defaultInstance);
  }

  public static com.ibc.core.client.v1.ConsensusStateWithHeight getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ConsensusStateWithHeight> PARSER;

  public static com.google.protobuf.Parser<ConsensusStateWithHeight> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

