// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/crypto/proof.proto

package com.tendermint.crypto;

/**
 * Protobuf type {@code tendermint.crypto.DominoOp}
 */
public  final class DominoOp extends
    com.google.protobuf.GeneratedMessageLite<
        DominoOp, DominoOp.Builder> implements
    // @@protoc_insertion_point(message_implements:tendermint.crypto.DominoOp)
    DominoOpOrBuilder {
  private DominoOp() {
    key_ = "";
    input_ = "";
    output_ = "";
  }
  public static final int KEY_FIELD_NUMBER = 1;
  private java.lang.String key_;
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The key to set.
   */
  private void setKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    key_ = value;
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   */
  private void clearKey() {
    
    key_ = getDefaultInstance().getKey();
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The bytes for key to set.
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    key_ = value.toStringUtf8();
    
  }

  public static final int INPUT_FIELD_NUMBER = 2;
  private java.lang.String input_;
  /**
   * <code>string input = 2 [json_name = "input"];</code>
   * @return The input.
   */
  @java.lang.Override
  public java.lang.String getInput() {
    return input_;
  }
  /**
   * <code>string input = 2 [json_name = "input"];</code>
   * @return The bytes for input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(input_);
  }
  /**
   * <code>string input = 2 [json_name = "input"];</code>
   * @param value The input to set.
   */
  private void setInput(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    input_ = value;
  }
  /**
   * <code>string input = 2 [json_name = "input"];</code>
   */
  private void clearInput() {
    
    input_ = getDefaultInstance().getInput();
  }
  /**
   * <code>string input = 2 [json_name = "input"];</code>
   * @param value The bytes for input to set.
   */
  private void setInputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    input_ = value.toStringUtf8();
    
  }

  public static final int OUTPUT_FIELD_NUMBER = 3;
  private java.lang.String output_;
  /**
   * <code>string output = 3 [json_name = "output"];</code>
   * @return The output.
   */
  @java.lang.Override
  public java.lang.String getOutput() {
    return output_;
  }
  /**
   * <code>string output = 3 [json_name = "output"];</code>
   * @return The bytes for output.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(output_);
  }
  /**
   * <code>string output = 3 [json_name = "output"];</code>
   * @param value The output to set.
   */
  private void setOutput(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    output_ = value;
  }
  /**
   * <code>string output = 3 [json_name = "output"];</code>
   */
  private void clearOutput() {
    
    output_ = getDefaultInstance().getOutput();
  }
  /**
   * <code>string output = 3 [json_name = "output"];</code>
   * @param value The bytes for output to set.
   */
  private void setOutputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    output_ = value.toStringUtf8();
    
  }

  public static com.tendermint.crypto.DominoOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.crypto.DominoOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.crypto.DominoOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.crypto.DominoOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.tendermint.crypto.DominoOp prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code tendermint.crypto.DominoOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.tendermint.crypto.DominoOp, Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.crypto.DominoOp)
      com.tendermint.crypto.DominoOpOrBuilder {
    // Construct using com.tendermint.crypto.DominoOp.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <code>string input = 2 [json_name = "input"];</code>
     * @return The input.
     */
    @java.lang.Override
    public java.lang.String getInput() {
      return instance.getInput();
    }
    /**
     * <code>string input = 2 [json_name = "input"];</code>
     * @return The bytes for input.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputBytes() {
      return instance.getInputBytes();
    }
    /**
     * <code>string input = 2 [json_name = "input"];</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(
        java.lang.String value) {
      copyOnWrite();
      instance.setInput(value);
      return this;
    }
    /**
     * <code>string input = 2 [json_name = "input"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      copyOnWrite();
      instance.clearInput();
      return this;
    }
    /**
     * <code>string input = 2 [json_name = "input"];</code>
     * @param value The bytes for input to set.
     * @return This builder for chaining.
     */
    public Builder setInputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInputBytes(value);
      return this;
    }

    /**
     * <code>string output = 3 [json_name = "output"];</code>
     * @return The output.
     */
    @java.lang.Override
    public java.lang.String getOutput() {
      return instance.getOutput();
    }
    /**
     * <code>string output = 3 [json_name = "output"];</code>
     * @return The bytes for output.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputBytes() {
      return instance.getOutputBytes();
    }
    /**
     * <code>string output = 3 [json_name = "output"];</code>
     * @param value The output to set.
     * @return This builder for chaining.
     */
    public Builder setOutput(
        java.lang.String value) {
      copyOnWrite();
      instance.setOutput(value);
      return this;
    }
    /**
     * <code>string output = 3 [json_name = "output"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutput() {
      copyOnWrite();
      instance.clearOutput();
      return this;
    }
    /**
     * <code>string output = 3 [json_name = "output"];</code>
     * @param value The bytes for output to set.
     * @return This builder for chaining.
     */
    public Builder setOutputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOutputBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tendermint.crypto.DominoOp)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.tendermint.crypto.DominoOp();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "key_",
            "input_",
            "output_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.tendermint.crypto.DominoOp> parser = PARSER;
        if (parser == null) {
          synchronized (com.tendermint.crypto.DominoOp.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.tendermint.crypto.DominoOp>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:tendermint.crypto.DominoOp)
  private static final com.tendermint.crypto.DominoOp DEFAULT_INSTANCE;
  static {
    DominoOp defaultInstance = new DominoOp();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DominoOp.class, defaultInstance);
  }

  public static com.tendermint.crypto.DominoOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DominoOp> PARSER;

  public static com.google.protobuf.Parser<DominoOp> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

