// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/crypto/proof.proto

package com.tendermint.crypto;

public interface ProofOpsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.crypto.ProofOps)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .tendermint.crypto.ProofOp ops = 1 [json_name = "ops", (.gogoproto.nullable) = false];</code>
   */
  java.util.List<com.tendermint.crypto.ProofOp> 
      getOpsList();
  /**
   * <code>repeated .tendermint.crypto.ProofOp ops = 1 [json_name = "ops", (.gogoproto.nullable) = false];</code>
   */
  com.tendermint.crypto.ProofOp getOps(int index);
  /**
   * <code>repeated .tendermint.crypto.ProofOp ops = 1 [json_name = "ops", (.gogoproto.nullable) = false];</code>
   */
  int getOpsCount();
}
