version: "3"

services:
  node:
    container_name: archway-node-1
    image: archwaynetwork/archwayd:v0.4.0
    build:
      context: .
    entrypoint:
      - sh
      - /opt/archway/localnet.sh
    ports:
      - 9090:9090
      - 26657:26657
    volumes:
      - ${PWD}/scripts:/opt:z
      - ${PWD}/artifacts/archway:/contracts:z
    working_dir: /opt
