// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/23-commitment/proofs.proto

package com.icon.proto.core.commitment;

/**
 * Protobuf enum {@code icon.proto.core.commitment.HashOp}
 */
public enum HashOp
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * NO_HASH is the default if no data passed. Note this is an illegal argument some places.
   * </pre>
   *
   * <code>NO_HASH = 0;</code>
   */
  NO_HASH(0),
  /**
   * <code>SHA256 = 1;</code>
   */
  SHA256(1),
  /**
   * <code>SHA512 = 2;</code>
   */
  SHA512(2),
  /**
   * <code>KECCAK = 3;</code>
   */
  KECCAK(3),
  /**
   * <code>RIPEMD160 = 4;</code>
   */
  RIPEMD160(4),
  /**
   * <pre>
   * ripemd160(sha256(x))
   * </pre>
   *
   * <code>BITCOIN = 5;</code>
   */
  BITCOIN(5),
  /**
   * <code>SHA512_256 = 6;</code>
   */
  SHA512_256(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * NO_HASH is the default if no data passed. Note this is an illegal argument some places.
   * </pre>
   *
   * <code>NO_HASH = 0;</code>
   */
  public static final int NO_HASH_VALUE = 0;
  /**
   * <code>SHA256 = 1;</code>
   */
  public static final int SHA256_VALUE = 1;
  /**
   * <code>SHA512 = 2;</code>
   */
  public static final int SHA512_VALUE = 2;
  /**
   * <code>KECCAK = 3;</code>
   */
  public static final int KECCAK_VALUE = 3;
  /**
   * <code>RIPEMD160 = 4;</code>
   */
  public static final int RIPEMD160_VALUE = 4;
  /**
   * <pre>
   * ripemd160(sha256(x))
   * </pre>
   *
   * <code>BITCOIN = 5;</code>
   */
  public static final int BITCOIN_VALUE = 5;
  /**
   * <code>SHA512_256 = 6;</code>
   */
  public static final int SHA512_256_VALUE = 6;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HashOp valueOf(int value) {
    return forNumber(value);
  }

  public static HashOp forNumber(int value) {
    switch (value) {
      case 0: return NO_HASH;
      case 1: return SHA256;
      case 2: return SHA512;
      case 3: return KECCAK;
      case 4: return RIPEMD160;
      case 5: return BITCOIN;
      case 6: return SHA512_256;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HashOp>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HashOp> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HashOp>() {
          @java.lang.Override
          public HashOp findValueByNumber(int number) {
            return HashOp.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return HashOpVerifier.INSTANCE;
  }

  private static final class HashOpVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new HashOpVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return HashOp.forNumber(number) != null;
          }
        };

  private final int value;

  private HashOp(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:icon.proto.core.commitment.HashOp)
}

