// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/23-commitment/proofs.proto

package com.icon.proto.core.commitment;

public interface InnerOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:icon.proto.core.commitment.InnerOp)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.icon.proto.core.commitment.HashOp hash = 1 [json_name = "hash"];</code>
   * @return The enum numeric value on the wire for hash.
   */
  int getHashValue();
  /**
   * <code>.icon.proto.core.commitment.HashOp hash = 1 [json_name = "hash"];</code>
   * @return The hash.
   */
  com.icon.proto.core.commitment.HashOp getHash();

  /**
   * <code>bytes prefix = 2 [json_name = "prefix"];</code>
   * @return The prefix.
   */
  com.google.protobuf.ByteString getPrefix();

  /**
   * <code>bytes suffix = 3 [json_name = "suffix"];</code>
   * @return The suffix.
   */
  com.google.protobuf.ByteString getSuffix();
}
