name: Test Java contracts

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'contracts/javascore/**'
  push:
    branches:
      - main
    paths:
      - 'contracts/javascore/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run unit tests
        run: cd contracts/javascore && ./gradlew clean build optimizedJar