[package]
name = "libraries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-storage-plus = "1.0.1"
cosmwasm-std = "1.1.3"
cosmwasm = "0.7.2"