// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients/tendermint/TendermintLight.proto

package com.ibc.lightclients.tendermint.v1;

public interface ConsensusStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibc.lightclients.tendermint.v1.ConsensusState)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * timestamp that corresponds to the block height in which the ConsensusState
   * was stored.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * timestamp that corresponds to the block height in which the ConsensusState
   * was stored.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();

  /**
   * <pre>
   * commitment root (i.e app hash)
   * </pre>
   *
   * <code>.ibc.core.commitment.v1.MerkleRoot root = 2 [json_name = "root", (.gogoproto.nullable) = false];</code>
   * @return Whether the root field is set.
   */
  boolean hasRoot();
  /**
   * <pre>
   * commitment root (i.e app hash)
   * </pre>
   *
   * <code>.ibc.core.commitment.v1.MerkleRoot root = 2 [json_name = "root", (.gogoproto.nullable) = false];</code>
   * @return The root.
   */
  com.ibc.core.commitment.v1.MerkleRoot getRoot();

  /**
   * <code>bytes next_validators_hash = 3 [json_name = "nextValidatorsHash", (.gogoproto.casttype) = "github.com/cometbft/cometbft/libs/bytes.HexBytes"];</code>
   * @return The nextValidatorsHash.
   */
  com.google.protobuf.ByteString getNextValidatorsHash();
}
