// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/types.proto

package com.tendermint.types;

/**
 * <pre>
 * BlockID
 * </pre>
 *
 * Protobuf type {@code tendermint.types.BlockID}
 */
public  final class BlockID extends
    com.google.protobuf.GeneratedMessageLite<
        BlockID, BlockID.Builder> implements
    // @@protoc_insertion_point(message_implements:tendermint.types.BlockID)
    BlockIDOrBuilder {
  private BlockID() {
    hash_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int HASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString hash_;
  /**
   * <code>bytes hash = 1 [json_name = "hash"];</code>
   * @return The hash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHash() {
    return hash_;
  }
  /**
   * <code>bytes hash = 1 [json_name = "hash"];</code>
   * @param value The hash to set.
   */
  private void setHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    hash_ = value;
  }
  /**
   * <code>bytes hash = 1 [json_name = "hash"];</code>
   */
  private void clearHash() {
    
    hash_ = getDefaultInstance().getHash();
  }

  public static final int PART_SET_HEADER_FIELD_NUMBER = 2;
  private com.tendermint.types.PartSetHeader partSetHeader_;
  /**
   * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public boolean hasPartSetHeader() {
    return partSetHeader_ != null;
  }
  /**
   * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.tendermint.types.PartSetHeader getPartSetHeader() {
    return partSetHeader_ == null ? com.tendermint.types.PartSetHeader.getDefaultInstance() : partSetHeader_;
  }
  /**
   * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
   */
  private void setPartSetHeader(com.tendermint.types.PartSetHeader value) {
    value.getClass();
  partSetHeader_ = value;
    
    }
  /**
   * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePartSetHeader(com.tendermint.types.PartSetHeader value) {
    value.getClass();
  if (partSetHeader_ != null &&
        partSetHeader_ != com.tendermint.types.PartSetHeader.getDefaultInstance()) {
      partSetHeader_ =
        com.tendermint.types.PartSetHeader.newBuilder(partSetHeader_).mergeFrom(value).buildPartial();
    } else {
      partSetHeader_ = value;
    }
    
  }
  /**
   * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
   */
  private void clearPartSetHeader() {  partSetHeader_ = null;
    
  }

  public static com.tendermint.types.BlockID parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.BlockID parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.BlockID parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.BlockID parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.BlockID parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.BlockID parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.BlockID parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.BlockID parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.BlockID parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.BlockID parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.BlockID parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.BlockID parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.tendermint.types.BlockID prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * BlockID
   * </pre>
   *
   * Protobuf type {@code tendermint.types.BlockID}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.tendermint.types.BlockID, Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.types.BlockID)
      com.tendermint.types.BlockIDOrBuilder {
    // Construct using com.tendermint.types.BlockID.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes hash = 1 [json_name = "hash"];</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return instance.getHash();
    }
    /**
     * <code>bytes hash = 1 [json_name = "hash"];</code>
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHash(value);
      return this;
    }
    /**
     * <code>bytes hash = 1 [json_name = "hash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHash() {
      copyOnWrite();
      instance.clearHash();
      return this;
    }

    /**
     * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public boolean hasPartSetHeader() {
      return instance.hasPartSetHeader();
    }
    /**
     * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public com.tendermint.types.PartSetHeader getPartSetHeader() {
      return instance.getPartSetHeader();
    }
    /**
     * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
     */
    public Builder setPartSetHeader(com.tendermint.types.PartSetHeader value) {
      copyOnWrite();
      instance.setPartSetHeader(value);
      return this;
      }
    /**
     * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
     */
    public Builder setPartSetHeader(
        com.tendermint.types.PartSetHeader.Builder builderForValue) {
      copyOnWrite();
      instance.setPartSetHeader(builderForValue.build());
      return this;
    }
    /**
     * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
     */
    public Builder mergePartSetHeader(com.tendermint.types.PartSetHeader value) {
      copyOnWrite();
      instance.mergePartSetHeader(value);
      return this;
    }
    /**
     * <code>.tendermint.types.PartSetHeader part_set_header = 2 [json_name = "partSetHeader", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearPartSetHeader() {  copyOnWrite();
      instance.clearPartSetHeader();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tendermint.types.BlockID)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.tendermint.types.BlockID();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "hash_",
            "partSetHeader_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0002\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.tendermint.types.BlockID> parser = PARSER;
        if (parser == null) {
          synchronized (com.tendermint.types.BlockID.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.tendermint.types.BlockID>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:tendermint.types.BlockID)
  private static final com.tendermint.types.BlockID DEFAULT_INSTANCE;
  static {
    BlockID defaultInstance = new BlockID();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BlockID.class, defaultInstance);
  }

  public static com.tendermint.types.BlockID getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BlockID> PARSER;

  public static com.google.protobuf.Parser<BlockID> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

