// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/types.proto

package com.tendermint.types;

/**
 * <pre>
 * Commit contains the evidence that a block was committed by a set of validators.
 * </pre>
 *
 * Protobuf type {@code tendermint.types.Commit}
 */
public  final class Commit extends
    com.google.protobuf.GeneratedMessageLite<
        Commit, Commit.Builder> implements
    // @@protoc_insertion_point(message_implements:tendermint.types.Commit)
    CommitOrBuilder {
  private Commit() {
    signatures_ = emptyProtobufList();
  }
  public static final int HEIGHT_FIELD_NUMBER = 1;
  private long height_;
  /**
   * <code>int64 height = 1 [json_name = "height"];</code>
   * @return The height.
   */
  @java.lang.Override
  public long getHeight() {
    return height_;
  }
  /**
   * <code>int64 height = 1 [json_name = "height"];</code>
   * @param value The height to set.
   */
  private void setHeight(long value) {
    
    height_ = value;
  }
  /**
   * <code>int64 height = 1 [json_name = "height"];</code>
   */
  private void clearHeight() {
    
    height_ = 0L;
  }

  public static final int ROUND_FIELD_NUMBER = 2;
  private int round_;
  /**
   * <code>int32 round = 2 [json_name = "round"];</code>
   * @return The round.
   */
  @java.lang.Override
  public int getRound() {
    return round_;
  }
  /**
   * <code>int32 round = 2 [json_name = "round"];</code>
   * @param value The round to set.
   */
  private void setRound(int value) {
    
    round_ = value;
  }
  /**
   * <code>int32 round = 2 [json_name = "round"];</code>
   */
  private void clearRound() {
    
    round_ = 0;
  }

  public static final int BLOCK_ID_FIELD_NUMBER = 3;
  private com.tendermint.types.BlockID blockId_;
  /**
   * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
   */
  @java.lang.Override
  public boolean hasBlockId() {
    return blockId_ != null;
  }
  /**
   * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
   */
  @java.lang.Override
  public com.tendermint.types.BlockID getBlockId() {
    return blockId_ == null ? com.tendermint.types.BlockID.getDefaultInstance() : blockId_;
  }
  /**
   * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
   */
  private void setBlockId(com.tendermint.types.BlockID value) {
    value.getClass();
  blockId_ = value;
    
    }
  /**
   * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBlockId(com.tendermint.types.BlockID value) {
    value.getClass();
  if (blockId_ != null &&
        blockId_ != com.tendermint.types.BlockID.getDefaultInstance()) {
      blockId_ =
        com.tendermint.types.BlockID.newBuilder(blockId_).mergeFrom(value).buildPartial();
    } else {
      blockId_ = value;
    }
    
  }
  /**
   * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
   */
  private void clearBlockId() {  blockId_ = null;
    
  }

  public static final int SIGNATURES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.tendermint.types.CommitSig> signatures_;
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public java.util.List<com.tendermint.types.CommitSig> getSignaturesList() {
    return signatures_;
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  public java.util.List<? extends com.tendermint.types.CommitSigOrBuilder> 
      getSignaturesOrBuilderList() {
    return signatures_;
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public int getSignaturesCount() {
    return signatures_.size();
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.tendermint.types.CommitSig getSignatures(int index) {
    return signatures_.get(index);
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  public com.tendermint.types.CommitSigOrBuilder getSignaturesOrBuilder(
      int index) {
    return signatures_.get(index);
  }
  private void ensureSignaturesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.tendermint.types.CommitSig> tmp = signatures_;
    if (!tmp.isModifiable()) {
      signatures_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  private void setSignatures(
      int index, com.tendermint.types.CommitSig value) {
    value.getClass();
  ensureSignaturesIsMutable();
    signatures_.set(index, value);
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  private void addSignatures(com.tendermint.types.CommitSig value) {
    value.getClass();
  ensureSignaturesIsMutable();
    signatures_.add(value);
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  private void addSignatures(
      int index, com.tendermint.types.CommitSig value) {
    value.getClass();
  ensureSignaturesIsMutable();
    signatures_.add(index, value);
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  private void addAllSignatures(
      java.lang.Iterable<? extends com.tendermint.types.CommitSig> values) {
    ensureSignaturesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, signatures_);
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  private void clearSignatures() {
    signatures_ = emptyProtobufList();
  }
  /**
   * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
   */
  private void removeSignatures(int index) {
    ensureSignaturesIsMutable();
    signatures_.remove(index);
  }

  public static com.tendermint.types.Commit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.Commit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.Commit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.Commit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.Commit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.Commit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.Commit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.Commit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.Commit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.Commit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.Commit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.Commit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.tendermint.types.Commit prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Commit contains the evidence that a block was committed by a set of validators.
   * </pre>
   *
   * Protobuf type {@code tendermint.types.Commit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.tendermint.types.Commit, Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.types.Commit)
      com.tendermint.types.CommitOrBuilder {
    // Construct using com.tendermint.types.Commit.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 height = 1 [json_name = "height"];</code>
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return instance.getHeight();
    }
    /**
     * <code>int64 height = 1 [json_name = "height"];</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {
      copyOnWrite();
      instance.setHeight(value);
      return this;
    }
    /**
     * <code>int64 height = 1 [json_name = "height"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      copyOnWrite();
      instance.clearHeight();
      return this;
    }

    /**
     * <code>int32 round = 2 [json_name = "round"];</code>
     * @return The round.
     */
    @java.lang.Override
    public int getRound() {
      return instance.getRound();
    }
    /**
     * <code>int32 round = 2 [json_name = "round"];</code>
     * @param value The round to set.
     * @return This builder for chaining.
     */
    public Builder setRound(int value) {
      copyOnWrite();
      instance.setRound(value);
      return this;
    }
    /**
     * <code>int32 round = 2 [json_name = "round"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRound() {
      copyOnWrite();
      instance.clearRound();
      return this;
    }

    /**
     * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
     */
    @java.lang.Override
    public boolean hasBlockId() {
      return instance.hasBlockId();
    }
    /**
     * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
     */
    @java.lang.Override
    public com.tendermint.types.BlockID getBlockId() {
      return instance.getBlockId();
    }
    /**
     * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
     */
    public Builder setBlockId(com.tendermint.types.BlockID value) {
      copyOnWrite();
      instance.setBlockId(value);
      return this;
      }
    /**
     * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
     */
    public Builder setBlockId(
        com.tendermint.types.BlockID.Builder builderForValue) {
      copyOnWrite();
      instance.setBlockId(builderForValue.build());
      return this;
    }
    /**
     * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
     */
    public Builder mergeBlockId(com.tendermint.types.BlockID value) {
      copyOnWrite();
      instance.mergeBlockId(value);
      return this;
    }
    /**
     * <code>.tendermint.types.BlockID block_id = 3 [json_name = "blockId", (.gogoproto.nullable) = false, (.gogoproto.customname) = "BlockID"];</code>
     */
    public Builder clearBlockId() {  copyOnWrite();
      instance.clearBlockId();
      return this;
    }

    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<com.tendermint.types.CommitSig> getSignaturesList() {
      return java.util.Collections.unmodifiableList(
          instance.getSignaturesList());
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public int getSignaturesCount() {
      return instance.getSignaturesCount();
    }/**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public com.tendermint.types.CommitSig getSignatures(int index) {
      return instance.getSignatures(index);
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder setSignatures(
        int index, com.tendermint.types.CommitSig value) {
      copyOnWrite();
      instance.setSignatures(index, value);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder setSignatures(
        int index, com.tendermint.types.CommitSig.Builder builderForValue) {
      copyOnWrite();
      instance.setSignatures(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder addSignatures(com.tendermint.types.CommitSig value) {
      copyOnWrite();
      instance.addSignatures(value);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder addSignatures(
        int index, com.tendermint.types.CommitSig value) {
      copyOnWrite();
      instance.addSignatures(index, value);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder addSignatures(
        com.tendermint.types.CommitSig.Builder builderForValue) {
      copyOnWrite();
      instance.addSignatures(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder addSignatures(
        int index, com.tendermint.types.CommitSig.Builder builderForValue) {
      copyOnWrite();
      instance.addSignatures(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder addAllSignatures(
        java.lang.Iterable<? extends com.tendermint.types.CommitSig> values) {
      copyOnWrite();
      instance.addAllSignatures(values);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearSignatures() {
      copyOnWrite();
      instance.clearSignatures();
      return this;
    }
    /**
     * <code>repeated .tendermint.types.CommitSig signatures = 4 [json_name = "signatures", (.gogoproto.nullable) = false];</code>
     */
    public Builder removeSignatures(int index) {
      copyOnWrite();
      instance.removeSignatures(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tendermint.types.Commit)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.tendermint.types.Commit();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "height_",
            "round_",
            "blockId_",
            "signatures_",
            com.tendermint.types.CommitSig.class,
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0002\u0002\u0004" +
              "\u0003\t\u0004\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.tendermint.types.Commit> parser = PARSER;
        if (parser == null) {
          synchronized (com.tendermint.types.Commit.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.tendermint.types.Commit>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:tendermint.types.Commit)
  private static final com.tendermint.types.Commit DEFAULT_INSTANCE;
  static {
    Commit defaultInstance = new Commit();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Commit.class, defaultInstance);
  }

  public static com.tendermint.types.Commit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Commit> PARSER;

  public static com.google.protobuf.Parser<Commit> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

