// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/types.proto

package com.tendermint.types;

/**
 * <pre>
 * Header defines the structure of a block header.
 * </pre>
 *
 * Protobuf type {@code tendermint.types.Header}
 */
public  final class Header extends
    com.google.protobuf.GeneratedMessageLite<
        Header, Header.Builder> implements
    // @@protoc_insertion_point(message_implements:tendermint.types.Header)
    HeaderOrBuilder {
  private Header() {
    chainId_ = "";
    lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
    dataHash_ = com.google.protobuf.ByteString.EMPTY;
    validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    consensusHash_ = com.google.protobuf.ByteString.EMPTY;
    appHash_ = com.google.protobuf.ByteString.EMPTY;
    lastResultsHash_ = com.google.protobuf.ByteString.EMPTY;
    evidenceHash_ = com.google.protobuf.ByteString.EMPTY;
    proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int VERSION_FIELD_NUMBER = 1;
  private com.tendermint.version.Consensus version_;
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.tendermint.version.Consensus getVersion() {
    return version_ == null ? com.tendermint.version.Consensus.getDefaultInstance() : version_;
  }
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   */
  private void setVersion(com.tendermint.version.Consensus value) {
    value.getClass();
  version_ = value;
    
    }
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVersion(com.tendermint.version.Consensus value) {
    value.getClass();
  if (version_ != null &&
        version_ != com.tendermint.version.Consensus.getDefaultInstance()) {
      version_ =
        com.tendermint.version.Consensus.newBuilder(version_).mergeFrom(value).buildPartial();
    } else {
      version_ = value;
    }
    
  }
  /**
   * <pre>
   * basic block info
   * </pre>
   *
   * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
   */
  private void clearVersion() {  version_ = null;
    
  }

  public static final int CHAIN_ID_FIELD_NUMBER = 2;
  private java.lang.String chainId_;
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   * @return The chainId.
   */
  @java.lang.Override
  public java.lang.String getChainId() {
    return chainId_;
  }
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   * @return The bytes for chainId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(chainId_);
  }
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   * @param value The chainId to set.
   */
  private void setChainId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    chainId_ = value;
  }
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   */
  private void clearChainId() {
    
    chainId_ = getDefaultInstance().getChainId();
  }
  /**
   * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
   * @param value The bytes for chainId to set.
   */
  private void setChainIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    chainId_ = value.toStringUtf8();
    
  }

  public static final int HEIGHT_FIELD_NUMBER = 3;
  private long height_;
  /**
   * <code>int64 height = 3 [json_name = "height"];</code>
   * @return The height.
   */
  @java.lang.Override
  public long getHeight() {
    return height_;
  }
  /**
   * <code>int64 height = 3 [json_name = "height"];</code>
   * @param value The height to set.
   */
  private void setHeight(long value) {
    
    height_ = value;
  }
  /**
   * <code>int64 height = 3 [json_name = "height"];</code>
   */
  private void clearHeight() {
    
    height_ = 0L;
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp time_;
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   */
  @java.lang.Override
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTime() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   */
  private void setTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  time_ = value;
    
    }
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (time_ != null &&
        time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      time_ =
        com.google.protobuf.Timestamp.newBuilder(time_).mergeFrom(value).buildPartial();
    } else {
      time_ = value;
    }
    
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
   */
  private void clearTime() {  time_ = null;
    
  }

  public static final int LAST_BLOCK_ID_FIELD_NUMBER = 5;
  private com.tendermint.types.BlockID lastBlockId_;
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public boolean hasLastBlockId() {
    return lastBlockId_ != null;
  }
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.Override
  public com.tendermint.types.BlockID getLastBlockId() {
    return lastBlockId_ == null ? com.tendermint.types.BlockID.getDefaultInstance() : lastBlockId_;
  }
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   */
  private void setLastBlockId(com.tendermint.types.BlockID value) {
    value.getClass();
  lastBlockId_ = value;
    
    }
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeLastBlockId(com.tendermint.types.BlockID value) {
    value.getClass();
  if (lastBlockId_ != null &&
        lastBlockId_ != com.tendermint.types.BlockID.getDefaultInstance()) {
      lastBlockId_ =
        com.tendermint.types.BlockID.newBuilder(lastBlockId_).mergeFrom(value).buildPartial();
    } else {
      lastBlockId_ = value;
    }
    
  }
  /**
   * <pre>
   * prev block info
   * </pre>
   *
   * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
   */
  private void clearLastBlockId() {  lastBlockId_ = null;
    
  }

  public static final int LAST_COMMIT_HASH_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString lastCommitHash_;
  /**
   * <pre>
   * hashes of block data
   * </pre>
   *
   * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
   * @return The lastCommitHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLastCommitHash() {
    return lastCommitHash_;
  }
  /**
   * <pre>
   * hashes of block data
   * </pre>
   *
   * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
   * @param value The lastCommitHash to set.
   */
  private void setLastCommitHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    lastCommitHash_ = value;
  }
  /**
   * <pre>
   * hashes of block data
   * </pre>
   *
   * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
   */
  private void clearLastCommitHash() {
    
    lastCommitHash_ = getDefaultInstance().getLastCommitHash();
  }

  public static final int DATA_HASH_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString dataHash_;
  /**
   * <pre>
   * transactions
   * </pre>
   *
   * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
   * @return The dataHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDataHash() {
    return dataHash_;
  }
  /**
   * <pre>
   * transactions
   * </pre>
   *
   * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
   * @param value The dataHash to set.
   */
  private void setDataHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    dataHash_ = value;
  }
  /**
   * <pre>
   * transactions
   * </pre>
   *
   * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
   */
  private void clearDataHash() {
    
    dataHash_ = getDefaultInstance().getDataHash();
  }

  public static final int VALIDATORS_HASH_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString validatorsHash_;
  /**
   * <pre>
   * hashes from the app output from the prev block
   * </pre>
   *
   * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
   * @return The validatorsHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValidatorsHash() {
    return validatorsHash_;
  }
  /**
   * <pre>
   * hashes from the app output from the prev block
   * </pre>
   *
   * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
   * @param value The validatorsHash to set.
   */
  private void setValidatorsHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    validatorsHash_ = value;
  }
  /**
   * <pre>
   * hashes from the app output from the prev block
   * </pre>
   *
   * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
   */
  private void clearValidatorsHash() {
    
    validatorsHash_ = getDefaultInstance().getValidatorsHash();
  }

  public static final int NEXT_VALIDATORS_HASH_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString nextValidatorsHash_;
  /**
   * <pre>
   * validators for the next block
   * </pre>
   *
   * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
   * @return The nextValidatorsHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNextValidatorsHash() {
    return nextValidatorsHash_;
  }
  /**
   * <pre>
   * validators for the next block
   * </pre>
   *
   * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
   * @param value The nextValidatorsHash to set.
   */
  private void setNextValidatorsHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nextValidatorsHash_ = value;
  }
  /**
   * <pre>
   * validators for the next block
   * </pre>
   *
   * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
   */
  private void clearNextValidatorsHash() {
    
    nextValidatorsHash_ = getDefaultInstance().getNextValidatorsHash();
  }

  public static final int CONSENSUS_HASH_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString consensusHash_;
  /**
   * <pre>
   * consensus params for current block
   * </pre>
   *
   * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
   * @return The consensusHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getConsensusHash() {
    return consensusHash_;
  }
  /**
   * <pre>
   * consensus params for current block
   * </pre>
   *
   * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
   * @param value The consensusHash to set.
   */
  private void setConsensusHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    consensusHash_ = value;
  }
  /**
   * <pre>
   * consensus params for current block
   * </pre>
   *
   * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
   */
  private void clearConsensusHash() {
    
    consensusHash_ = getDefaultInstance().getConsensusHash();
  }

  public static final int APP_HASH_FIELD_NUMBER = 11;
  private com.google.protobuf.ByteString appHash_;
  /**
   * <pre>
   * state after txs from the previous block
   * </pre>
   *
   * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
   * @return The appHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAppHash() {
    return appHash_;
  }
  /**
   * <pre>
   * state after txs from the previous block
   * </pre>
   *
   * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
   * @param value The appHash to set.
   */
  private void setAppHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    appHash_ = value;
  }
  /**
   * <pre>
   * state after txs from the previous block
   * </pre>
   *
   * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
   */
  private void clearAppHash() {
    
    appHash_ = getDefaultInstance().getAppHash();
  }

  public static final int LAST_RESULTS_HASH_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString lastResultsHash_;
  /**
   * <pre>
   * root hash of all results from the txs from the previous block
   * </pre>
   *
   * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
   * @return The lastResultsHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLastResultsHash() {
    return lastResultsHash_;
  }
  /**
   * <pre>
   * root hash of all results from the txs from the previous block
   * </pre>
   *
   * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
   * @param value The lastResultsHash to set.
   */
  private void setLastResultsHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    lastResultsHash_ = value;
  }
  /**
   * <pre>
   * root hash of all results from the txs from the previous block
   * </pre>
   *
   * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
   */
  private void clearLastResultsHash() {
    
    lastResultsHash_ = getDefaultInstance().getLastResultsHash();
  }

  public static final int EVIDENCE_HASH_FIELD_NUMBER = 13;
  private com.google.protobuf.ByteString evidenceHash_;
  /**
   * <pre>
   * consensus info
   * </pre>
   *
   * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
   * @return The evidenceHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEvidenceHash() {
    return evidenceHash_;
  }
  /**
   * <pre>
   * consensus info
   * </pre>
   *
   * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
   * @param value The evidenceHash to set.
   */
  private void setEvidenceHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    evidenceHash_ = value;
  }
  /**
   * <pre>
   * consensus info
   * </pre>
   *
   * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
   */
  private void clearEvidenceHash() {
    
    evidenceHash_ = getDefaultInstance().getEvidenceHash();
  }

  public static final int PROPOSER_ADDRESS_FIELD_NUMBER = 14;
  private com.google.protobuf.ByteString proposerAddress_;
  /**
   * <pre>
   * original proposer of the block
   * </pre>
   *
   * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
   * @return The proposerAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProposerAddress() {
    return proposerAddress_;
  }
  /**
   * <pre>
   * original proposer of the block
   * </pre>
   *
   * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
   * @param value The proposerAddress to set.
   */
  private void setProposerAddress(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    proposerAddress_ = value;
  }
  /**
   * <pre>
   * original proposer of the block
   * </pre>
   *
   * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
   */
  private void clearProposerAddress() {
    
    proposerAddress_ = getDefaultInstance().getProposerAddress();
  }

  public static com.tendermint.types.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.tendermint.types.Header prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Header defines the structure of a block header.
   * </pre>
   *
   * Protobuf type {@code tendermint.types.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.tendermint.types.Header, Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.types.Header)
      com.tendermint.types.HeaderOrBuilder {
    // Construct using com.tendermint.types.Header.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public com.tendermint.version.Consensus getVersion() {
      return instance.getVersion();
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder setVersion(com.tendermint.version.Consensus value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
      }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder setVersion(
        com.tendermint.version.Consensus.Builder builderForValue) {
      copyOnWrite();
      instance.setVersion(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder mergeVersion(com.tendermint.version.Consensus value) {
      copyOnWrite();
      instance.mergeVersion(value);
      return this;
    }
    /**
     * <pre>
     * basic block info
     * </pre>
     *
     * <code>.tendermint.version.Consensus version = 1 [json_name = "version", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearVersion() {  copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @return The chainId.
     */
    @java.lang.Override
    public java.lang.String getChainId() {
      return instance.getChainId();
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @return The bytes for chainId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChainIdBytes() {
      return instance.getChainIdBytes();
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @param value The chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainId(
        java.lang.String value) {
      copyOnWrite();
      instance.setChainId(value);
      return this;
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChainId() {
      copyOnWrite();
      instance.clearChainId();
      return this;
    }
    /**
     * <code>string chain_id = 2 [json_name = "chainId", (.gogoproto.customname) = "ChainID"];</code>
     * @param value The bytes for chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChainIdBytes(value);
      return this;
    }

    /**
     * <code>int64 height = 3 [json_name = "height"];</code>
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return instance.getHeight();
    }
    /**
     * <code>int64 height = 3 [json_name = "height"];</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {
      copyOnWrite();
      instance.setHeight(value);
      return this;
    }
    /**
     * <code>int64 height = 3 [json_name = "height"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      copyOnWrite();
      instance.clearHeight();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    @java.lang.Override
    public boolean hasTime() {
      return instance.hasTime();
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTime() {
      return instance.getTime();
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder setTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setTime(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder setTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setTime(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder mergeTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeTime(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4 [json_name = "time", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    public Builder clearTime() {  copyOnWrite();
      instance.clearTime();
      return this;
    }

    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public boolean hasLastBlockId() {
      return instance.hasLastBlockId();
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public com.tendermint.types.BlockID getLastBlockId() {
      return instance.getLastBlockId();
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder setLastBlockId(com.tendermint.types.BlockID value) {
      copyOnWrite();
      instance.setLastBlockId(value);
      return this;
      }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder setLastBlockId(
        com.tendermint.types.BlockID.Builder builderForValue) {
      copyOnWrite();
      instance.setLastBlockId(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder mergeLastBlockId(com.tendermint.types.BlockID value) {
      copyOnWrite();
      instance.mergeLastBlockId(value);
      return this;
    }
    /**
     * <pre>
     * prev block info
     * </pre>
     *
     * <code>.tendermint.types.BlockID last_block_id = 5 [json_name = "lastBlockId", (.gogoproto.nullable) = false];</code>
     */
    public Builder clearLastBlockId() {  copyOnWrite();
      instance.clearLastBlockId();
      return this;
    }

    /**
     * <pre>
     * hashes of block data
     * </pre>
     *
     * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
     * @return The lastCommitHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLastCommitHash() {
      return instance.getLastCommitHash();
    }
    /**
     * <pre>
     * hashes of block data
     * </pre>
     *
     * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
     * @param value The lastCommitHash to set.
     * @return This builder for chaining.
     */
    public Builder setLastCommitHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLastCommitHash(value);
      return this;
    }
    /**
     * <pre>
     * hashes of block data
     * </pre>
     *
     * <code>bytes last_commit_hash = 6 [json_name = "lastCommitHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCommitHash() {
      copyOnWrite();
      instance.clearLastCommitHash();
      return this;
    }

    /**
     * <pre>
     * transactions
     * </pre>
     *
     * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
     * @return The dataHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataHash() {
      return instance.getDataHash();
    }
    /**
     * <pre>
     * transactions
     * </pre>
     *
     * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
     * @param value The dataHash to set.
     * @return This builder for chaining.
     */
    public Builder setDataHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDataHash(value);
      return this;
    }
    /**
     * <pre>
     * transactions
     * </pre>
     *
     * <code>bytes data_hash = 7 [json_name = "dataHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDataHash() {
      copyOnWrite();
      instance.clearDataHash();
      return this;
    }

    /**
     * <pre>
     * hashes from the app output from the prev block
     * </pre>
     *
     * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
     * @return The validatorsHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValidatorsHash() {
      return instance.getValidatorsHash();
    }
    /**
     * <pre>
     * hashes from the app output from the prev block
     * </pre>
     *
     * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
     * @param value The validatorsHash to set.
     * @return This builder for chaining.
     */
    public Builder setValidatorsHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValidatorsHash(value);
      return this;
    }
    /**
     * <pre>
     * hashes from the app output from the prev block
     * </pre>
     *
     * <code>bytes validators_hash = 8 [json_name = "validatorsHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValidatorsHash() {
      copyOnWrite();
      instance.clearValidatorsHash();
      return this;
    }

    /**
     * <pre>
     * validators for the next block
     * </pre>
     *
     * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
     * @return The nextValidatorsHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNextValidatorsHash() {
      return instance.getNextValidatorsHash();
    }
    /**
     * <pre>
     * validators for the next block
     * </pre>
     *
     * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
     * @param value The nextValidatorsHash to set.
     * @return This builder for chaining.
     */
    public Builder setNextValidatorsHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextValidatorsHash(value);
      return this;
    }
    /**
     * <pre>
     * validators for the next block
     * </pre>
     *
     * <code>bytes next_validators_hash = 9 [json_name = "nextValidatorsHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNextValidatorsHash() {
      copyOnWrite();
      instance.clearNextValidatorsHash();
      return this;
    }

    /**
     * <pre>
     * consensus params for current block
     * </pre>
     *
     * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
     * @return The consensusHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getConsensusHash() {
      return instance.getConsensusHash();
    }
    /**
     * <pre>
     * consensus params for current block
     * </pre>
     *
     * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
     * @param value The consensusHash to set.
     * @return This builder for chaining.
     */
    public Builder setConsensusHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConsensusHash(value);
      return this;
    }
    /**
     * <pre>
     * consensus params for current block
     * </pre>
     *
     * <code>bytes consensus_hash = 10 [json_name = "consensusHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConsensusHash() {
      copyOnWrite();
      instance.clearConsensusHash();
      return this;
    }

    /**
     * <pre>
     * state after txs from the previous block
     * </pre>
     *
     * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
     * @return The appHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAppHash() {
      return instance.getAppHash();
    }
    /**
     * <pre>
     * state after txs from the previous block
     * </pre>
     *
     * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
     * @param value The appHash to set.
     * @return This builder for chaining.
     */
    public Builder setAppHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppHash(value);
      return this;
    }
    /**
     * <pre>
     * state after txs from the previous block
     * </pre>
     *
     * <code>bytes app_hash = 11 [json_name = "appHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAppHash() {
      copyOnWrite();
      instance.clearAppHash();
      return this;
    }

    /**
     * <pre>
     * root hash of all results from the txs from the previous block
     * </pre>
     *
     * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
     * @return The lastResultsHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLastResultsHash() {
      return instance.getLastResultsHash();
    }
    /**
     * <pre>
     * root hash of all results from the txs from the previous block
     * </pre>
     *
     * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
     * @param value The lastResultsHash to set.
     * @return This builder for chaining.
     */
    public Builder setLastResultsHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLastResultsHash(value);
      return this;
    }
    /**
     * <pre>
     * root hash of all results from the txs from the previous block
     * </pre>
     *
     * <code>bytes last_results_hash = 12 [json_name = "lastResultsHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLastResultsHash() {
      copyOnWrite();
      instance.clearLastResultsHash();
      return this;
    }

    /**
     * <pre>
     * consensus info
     * </pre>
     *
     * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
     * @return The evidenceHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEvidenceHash() {
      return instance.getEvidenceHash();
    }
    /**
     * <pre>
     * consensus info
     * </pre>
     *
     * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
     * @param value The evidenceHash to set.
     * @return This builder for chaining.
     */
    public Builder setEvidenceHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEvidenceHash(value);
      return this;
    }
    /**
     * <pre>
     * consensus info
     * </pre>
     *
     * <code>bytes evidence_hash = 13 [json_name = "evidenceHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEvidenceHash() {
      copyOnWrite();
      instance.clearEvidenceHash();
      return this;
    }

    /**
     * <pre>
     * original proposer of the block
     * </pre>
     *
     * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
     * @return The proposerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProposerAddress() {
      return instance.getProposerAddress();
    }
    /**
     * <pre>
     * original proposer of the block
     * </pre>
     *
     * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
     * @param value The proposerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setProposerAddress(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProposerAddress(value);
      return this;
    }
    /**
     * <pre>
     * original proposer of the block
     * </pre>
     *
     * <code>bytes proposer_address = 14 [json_name = "proposerAddress"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProposerAddress() {
      copyOnWrite();
      instance.clearProposerAddress();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tendermint.types.Header)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.tendermint.types.Header();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "version_",
            "chainId_",
            "height_",
            "time_",
            "lastBlockId_",
            "lastCommitHash_",
            "dataHash_",
            "validatorsHash_",
            "nextValidatorsHash_",
            "consensusHash_",
            "appHash_",
            "lastResultsHash_",
            "evidenceHash_",
            "proposerAddress_",
          };
          java.lang.String info =
              "\u0000\u000e\u0000\u0000\u0001\u000e\u000e\u0000\u0000\u0000\u0001\t\u0002\u0208" +
              "\u0003\u0002\u0004\t\u0005\t\u0006\n\u0007\n\b\n\t\n\n\n\u000b\n\f\n\r\n\u000e\n" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.tendermint.types.Header> parser = PARSER;
        if (parser == null) {
          synchronized (com.tendermint.types.Header.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.tendermint.types.Header>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:tendermint.types.Header)
  private static final com.tendermint.types.Header DEFAULT_INSTANCE;
  static {
    Header defaultInstance = new Header();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Header.class, defaultInstance);
  }

  public static com.tendermint.types.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Header> PARSER;

  public static com.google.protobuf.Parser<Header> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

