// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/types/validator.proto

package com.tendermint.types;

/**
 * Protobuf type {@code tendermint.types.ValidatorSet}
 */
public  final class ValidatorSet extends
    com.google.protobuf.GeneratedMessageLite<
        ValidatorSet, ValidatorSet.Builder> implements
    // @@protoc_insertion_point(message_implements:tendermint.types.ValidatorSet)
    ValidatorSetOrBuilder {
  private ValidatorSet() {
    validators_ = emptyProtobufList();
  }
  public static final int VALIDATORS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.tendermint.types.Validator> validators_;
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tendermint.types.Validator> getValidatorsList() {
    return validators_;
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  public java.util.List<? extends com.tendermint.types.ValidatorOrBuilder> 
      getValidatorsOrBuilderList() {
    return validators_;
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  @java.lang.Override
  public int getValidatorsCount() {
    return validators_.size();
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  @java.lang.Override
  public com.tendermint.types.Validator getValidators(int index) {
    return validators_.get(index);
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  public com.tendermint.types.ValidatorOrBuilder getValidatorsOrBuilder(
      int index) {
    return validators_.get(index);
  }
  private void ensureValidatorsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.tendermint.types.Validator> tmp = validators_;
    if (!tmp.isModifiable()) {
      validators_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  private void setValidators(
      int index, com.tendermint.types.Validator value) {
    value.getClass();
  ensureValidatorsIsMutable();
    validators_.set(index, value);
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  private void addValidators(com.tendermint.types.Validator value) {
    value.getClass();
  ensureValidatorsIsMutable();
    validators_.add(value);
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  private void addValidators(
      int index, com.tendermint.types.Validator value) {
    value.getClass();
  ensureValidatorsIsMutable();
    validators_.add(index, value);
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  private void addAllValidators(
      java.lang.Iterable<? extends com.tendermint.types.Validator> values) {
    ensureValidatorsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, validators_);
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  private void clearValidators() {
    validators_ = emptyProtobufList();
  }
  /**
   * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
   */
  private void removeValidators(int index) {
    ensureValidatorsIsMutable();
    validators_.remove(index);
  }

  public static final int PROPOSER_FIELD_NUMBER = 2;
  private com.tendermint.types.Validator proposer_;
  /**
   * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
   */
  @java.lang.Override
  public boolean hasProposer() {
    return proposer_ != null;
  }
  /**
   * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
   */
  @java.lang.Override
  public com.tendermint.types.Validator getProposer() {
    return proposer_ == null ? com.tendermint.types.Validator.getDefaultInstance() : proposer_;
  }
  /**
   * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
   */
  private void setProposer(com.tendermint.types.Validator value) {
    value.getClass();
  proposer_ = value;
    
    }
  /**
   * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeProposer(com.tendermint.types.Validator value) {
    value.getClass();
  if (proposer_ != null &&
        proposer_ != com.tendermint.types.Validator.getDefaultInstance()) {
      proposer_ =
        com.tendermint.types.Validator.newBuilder(proposer_).mergeFrom(value).buildPartial();
    } else {
      proposer_ = value;
    }
    
  }
  /**
   * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
   */
  private void clearProposer() {  proposer_ = null;
    
  }

  public static final int TOTAL_VOTING_POWER_FIELD_NUMBER = 3;
  private long totalVotingPower_;
  /**
   * <code>int64 total_voting_power = 3 [json_name = "totalVotingPower"];</code>
   * @return The totalVotingPower.
   */
  @java.lang.Override
  public long getTotalVotingPower() {
    return totalVotingPower_;
  }
  /**
   * <code>int64 total_voting_power = 3 [json_name = "totalVotingPower"];</code>
   * @param value The totalVotingPower to set.
   */
  private void setTotalVotingPower(long value) {
    
    totalVotingPower_ = value;
  }
  /**
   * <code>int64 total_voting_power = 3 [json_name = "totalVotingPower"];</code>
   */
  private void clearTotalVotingPower() {
    
    totalVotingPower_ = 0L;
  }

  public static com.tendermint.types.ValidatorSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.ValidatorSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.ValidatorSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.tendermint.types.ValidatorSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.tendermint.types.ValidatorSet prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code tendermint.types.ValidatorSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.tendermint.types.ValidatorSet, Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.types.ValidatorSet)
      com.tendermint.types.ValidatorSetOrBuilder {
    // Construct using com.tendermint.types.ValidatorSet.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    @java.lang.Override
    public java.util.List<com.tendermint.types.Validator> getValidatorsList() {
      return java.util.Collections.unmodifiableList(
          instance.getValidatorsList());
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    @java.lang.Override
    public int getValidatorsCount() {
      return instance.getValidatorsCount();
    }/**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    @java.lang.Override
    public com.tendermint.types.Validator getValidators(int index) {
      return instance.getValidators(index);
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder setValidators(
        int index, com.tendermint.types.Validator value) {
      copyOnWrite();
      instance.setValidators(index, value);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder setValidators(
        int index, com.tendermint.types.Validator.Builder builderForValue) {
      copyOnWrite();
      instance.setValidators(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder addValidators(com.tendermint.types.Validator value) {
      copyOnWrite();
      instance.addValidators(value);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder addValidators(
        int index, com.tendermint.types.Validator value) {
      copyOnWrite();
      instance.addValidators(index, value);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder addValidators(
        com.tendermint.types.Validator.Builder builderForValue) {
      copyOnWrite();
      instance.addValidators(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder addValidators(
        int index, com.tendermint.types.Validator.Builder builderForValue) {
      copyOnWrite();
      instance.addValidators(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder addAllValidators(
        java.lang.Iterable<? extends com.tendermint.types.Validator> values) {
      copyOnWrite();
      instance.addAllValidators(values);
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder clearValidators() {
      copyOnWrite();
      instance.clearValidators();
      return this;
    }
    /**
     * <code>repeated .tendermint.types.Validator validators = 1 [json_name = "validators"];</code>
     */
    public Builder removeValidators(int index) {
      copyOnWrite();
      instance.removeValidators(index);
      return this;
    }

    /**
     * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
     */
    @java.lang.Override
    public boolean hasProposer() {
      return instance.hasProposer();
    }
    /**
     * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
     */
    @java.lang.Override
    public com.tendermint.types.Validator getProposer() {
      return instance.getProposer();
    }
    /**
     * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
     */
    public Builder setProposer(com.tendermint.types.Validator value) {
      copyOnWrite();
      instance.setProposer(value);
      return this;
      }
    /**
     * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
     */
    public Builder setProposer(
        com.tendermint.types.Validator.Builder builderForValue) {
      copyOnWrite();
      instance.setProposer(builderForValue.build());
      return this;
    }
    /**
     * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
     */
    public Builder mergeProposer(com.tendermint.types.Validator value) {
      copyOnWrite();
      instance.mergeProposer(value);
      return this;
    }
    /**
     * <code>.tendermint.types.Validator proposer = 2 [json_name = "proposer"];</code>
     */
    public Builder clearProposer() {  copyOnWrite();
      instance.clearProposer();
      return this;
    }

    /**
     * <code>int64 total_voting_power = 3 [json_name = "totalVotingPower"];</code>
     * @return The totalVotingPower.
     */
    @java.lang.Override
    public long getTotalVotingPower() {
      return instance.getTotalVotingPower();
    }
    /**
     * <code>int64 total_voting_power = 3 [json_name = "totalVotingPower"];</code>
     * @param value The totalVotingPower to set.
     * @return This builder for chaining.
     */
    public Builder setTotalVotingPower(long value) {
      copyOnWrite();
      instance.setTotalVotingPower(value);
      return this;
    }
    /**
     * <code>int64 total_voting_power = 3 [json_name = "totalVotingPower"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalVotingPower() {
      copyOnWrite();
      instance.clearTotalVotingPower();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tendermint.types.ValidatorSet)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.tendermint.types.ValidatorSet();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "validators_",
            com.tendermint.types.Validator.class,
            "proposer_",
            "totalVotingPower_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u001b\u0002\t" +
              "\u0003\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.tendermint.types.ValidatorSet> parser = PARSER;
        if (parser == null) {
          synchronized (com.tendermint.types.ValidatorSet.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.tendermint.types.ValidatorSet>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:tendermint.types.ValidatorSet)
  private static final com.tendermint.types.ValidatorSet DEFAULT_INSTANCE;
  static {
    ValidatorSet defaultInstance = new ValidatorSet();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ValidatorSet.class, defaultInstance);
  }

  public static com.tendermint.types.ValidatorSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ValidatorSet> PARSER;

  public static com.google.protobuf.Parser<ValidatorSet> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

