// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: icon/lightclient/v1/light.proto

package com.icon.lightclient.v1;

/**
 * Protobuf type {@code icon.lightclient.v1.TrustLevel}
 */
public  final class TrustLevel extends
    com.google.protobuf.GeneratedMessageLite<
        TrustLevel, TrustLevel.Builder> implements
    // @@protoc_insertion_point(message_implements:icon.lightclient.v1.TrustLevel)
    TrustLevelOrBuilder {
  private TrustLevel() {
  }
  public static final int NUMERATOR_FIELD_NUMBER = 1;
  private long numerator_;
  /**
   * <code>uint64 numerator = 1 [json_name = "numerator"];</code>
   * @return The numerator.
   */
  @java.lang.Override
  public long getNumerator() {
    return numerator_;
  }
  /**
   * <code>uint64 numerator = 1 [json_name = "numerator"];</code>
   * @param value The numerator to set.
   */
  private void setNumerator(long value) {
    
    numerator_ = value;
  }
  /**
   * <code>uint64 numerator = 1 [json_name = "numerator"];</code>
   */
  private void clearNumerator() {
    
    numerator_ = 0L;
  }

  public static final int DENOMINATOR_FIELD_NUMBER = 2;
  private long denominator_;
  /**
   * <code>uint64 denominator = 2 [json_name = "denominator"];</code>
   * @return The denominator.
   */
  @java.lang.Override
  public long getDenominator() {
    return denominator_;
  }
  /**
   * <code>uint64 denominator = 2 [json_name = "denominator"];</code>
   * @param value The denominator to set.
   */
  private void setDenominator(long value) {
    
    denominator_ = value;
  }
  /**
   * <code>uint64 denominator = 2 [json_name = "denominator"];</code>
   */
  private void clearDenominator() {
    
    denominator_ = 0L;
  }

  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.icon.lightclient.v1.TrustLevel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.icon.lightclient.v1.TrustLevel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.icon.lightclient.v1.TrustLevel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.icon.lightclient.v1.TrustLevel prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code icon.lightclient.v1.TrustLevel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.icon.lightclient.v1.TrustLevel, Builder> implements
      // @@protoc_insertion_point(builder_implements:icon.lightclient.v1.TrustLevel)
      com.icon.lightclient.v1.TrustLevelOrBuilder {
    // Construct using com.icon.lightclient.v1.TrustLevel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint64 numerator = 1 [json_name = "numerator"];</code>
     * @return The numerator.
     */
    @java.lang.Override
    public long getNumerator() {
      return instance.getNumerator();
    }
    /**
     * <code>uint64 numerator = 1 [json_name = "numerator"];</code>
     * @param value The numerator to set.
     * @return This builder for chaining.
     */
    public Builder setNumerator(long value) {
      copyOnWrite();
      instance.setNumerator(value);
      return this;
    }
    /**
     * <code>uint64 numerator = 1 [json_name = "numerator"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumerator() {
      copyOnWrite();
      instance.clearNumerator();
      return this;
    }

    /**
     * <code>uint64 denominator = 2 [json_name = "denominator"];</code>
     * @return The denominator.
     */
    @java.lang.Override
    public long getDenominator() {
      return instance.getDenominator();
    }
    /**
     * <code>uint64 denominator = 2 [json_name = "denominator"];</code>
     * @param value The denominator to set.
     * @return This builder for chaining.
     */
    public Builder setDenominator(long value) {
      copyOnWrite();
      instance.setDenominator(value);
      return this;
    }
    /**
     * <code>uint64 denominator = 2 [json_name = "denominator"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDenominator() {
      copyOnWrite();
      instance.clearDenominator();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:icon.lightclient.v1.TrustLevel)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.icon.lightclient.v1.TrustLevel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "numerator_",
            "denominator_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0003\u0002\u0003" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.icon.lightclient.v1.TrustLevel> parser = PARSER;
        if (parser == null) {
          synchronized (com.icon.lightclient.v1.TrustLevel.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.icon.lightclient.v1.TrustLevel>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:icon.lightclient.v1.TrustLevel)
  private static final com.icon.lightclient.v1.TrustLevel DEFAULT_INSTANCE;
  static {
    TrustLevel defaultInstance = new TrustLevel();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TrustLevel.class, defaultInstance);
  }

  public static com.icon.lightclient.v1.TrustLevel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TrustLevel> PARSER;

  public static com.google.protobuf.Parser<TrustLevel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

