// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gogoproto/gogo.proto

package com.gogoproto;

public final class GogoProto {
  private GogoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.gogoproto.GogoProto.goprotoEnumPrefix);
    registry.add(com.gogoproto.GogoProto.goprotoEnumStringer);
    registry.add(com.gogoproto.GogoProto.enumStringer);
    registry.add(com.gogoproto.GogoProto.enumCustomname);
    registry.add(com.gogoproto.GogoProto.enumdecl);
    registry.add(com.gogoproto.GogoProto.enumvalueCustomname);
    registry.add(com.gogoproto.GogoProto.goprotoGettersAll);
    registry.add(com.gogoproto.GogoProto.goprotoEnumPrefixAll);
    registry.add(com.gogoproto.GogoProto.goprotoStringerAll);
    registry.add(com.gogoproto.GogoProto.verboseEqualAll);
    registry.add(com.gogoproto.GogoProto.faceAll);
    registry.add(com.gogoproto.GogoProto.gostringAll);
    registry.add(com.gogoproto.GogoProto.populateAll);
    registry.add(com.gogoproto.GogoProto.stringerAll);
    registry.add(com.gogoproto.GogoProto.onlyoneAll);
    registry.add(com.gogoproto.GogoProto.equalAll);
    registry.add(com.gogoproto.GogoProto.descriptionAll);
    registry.add(com.gogoproto.GogoProto.testgenAll);
    registry.add(com.gogoproto.GogoProto.benchgenAll);
    registry.add(com.gogoproto.GogoProto.marshalerAll);
    registry.add(com.gogoproto.GogoProto.unmarshalerAll);
    registry.add(com.gogoproto.GogoProto.stableMarshalerAll);
    registry.add(com.gogoproto.GogoProto.sizerAll);
    registry.add(com.gogoproto.GogoProto.goprotoEnumStringerAll);
    registry.add(com.gogoproto.GogoProto.enumStringerAll);
    registry.add(com.gogoproto.GogoProto.unsafeMarshalerAll);
    registry.add(com.gogoproto.GogoProto.unsafeUnmarshalerAll);
    registry.add(com.gogoproto.GogoProto.goprotoExtensionsMapAll);
    registry.add(com.gogoproto.GogoProto.goprotoUnrecognizedAll);
    registry.add(com.gogoproto.GogoProto.gogoprotoImport);
    registry.add(com.gogoproto.GogoProto.protosizerAll);
    registry.add(com.gogoproto.GogoProto.compareAll);
    registry.add(com.gogoproto.GogoProto.typedeclAll);
    registry.add(com.gogoproto.GogoProto.enumdeclAll);
    registry.add(com.gogoproto.GogoProto.goprotoRegistration);
    registry.add(com.gogoproto.GogoProto.messagenameAll);
    registry.add(com.gogoproto.GogoProto.goprotoSizecacheAll);
    registry.add(com.gogoproto.GogoProto.goprotoUnkeyedAll);
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    registry.add(com.gogoproto.GogoProto.goprotoStringer);
    registry.add(com.gogoproto.GogoProto.verboseEqual);
    registry.add(com.gogoproto.GogoProto.face);
    registry.add(com.gogoproto.GogoProto.gostring);
    registry.add(com.gogoproto.GogoProto.populate);
    registry.add(com.gogoproto.GogoProto.stringer);
    registry.add(com.gogoproto.GogoProto.onlyone);
    registry.add(com.gogoproto.GogoProto.equal);
    registry.add(com.gogoproto.GogoProto.description);
    registry.add(com.gogoproto.GogoProto.testgen);
    registry.add(com.gogoproto.GogoProto.benchgen);
    registry.add(com.gogoproto.GogoProto.marshaler);
    registry.add(com.gogoproto.GogoProto.unmarshaler);
    registry.add(com.gogoproto.GogoProto.stableMarshaler);
    registry.add(com.gogoproto.GogoProto.sizer);
    registry.add(com.gogoproto.GogoProto.unsafeMarshaler);
    registry.add(com.gogoproto.GogoProto.unsafeUnmarshaler);
    registry.add(com.gogoproto.GogoProto.goprotoExtensionsMap);
    registry.add(com.gogoproto.GogoProto.goprotoUnrecognized);
    registry.add(com.gogoproto.GogoProto.protosizer);
    registry.add(com.gogoproto.GogoProto.compare);
    registry.add(com.gogoproto.GogoProto.typedecl);
    registry.add(com.gogoproto.GogoProto.messagename);
    registry.add(com.gogoproto.GogoProto.goprotoSizecache);
    registry.add(com.gogoproto.GogoProto.goprotoUnkeyed);
    registry.add(com.gogoproto.GogoProto.nullable);
    registry.add(com.gogoproto.GogoProto.embed);
    registry.add(com.gogoproto.GogoProto.customtype);
    registry.add(com.gogoproto.GogoProto.customname);
    registry.add(com.gogoproto.GogoProto.jsontag);
    registry.add(com.gogoproto.GogoProto.moretags);
    registry.add(com.gogoproto.GogoProto.casttype);
    registry.add(com.gogoproto.GogoProto.castkey);
    registry.add(com.gogoproto.GogoProto.castvalue);
    registry.add(com.gogoproto.GogoProto.stdtime);
    registry.add(com.gogoproto.GogoProto.stdduration);
    registry.add(com.gogoproto.GogoProto.wktpointer);
    registry.add(com.gogoproto.GogoProto.castrepeated);
  }
  public static final int GOPROTO_ENUM_PREFIX_FIELD_NUMBER = 62001;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> goprotoEnumPrefix = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.EnumOptions.getDefaultInstance(),
        false,
        null,
        null,
        62001,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_ENUM_STRINGER_FIELD_NUMBER = 62021;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> goprotoEnumStringer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.EnumOptions.getDefaultInstance(),
        false,
        null,
        null,
        62021,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ENUM_STRINGER_FIELD_NUMBER = 62022;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumStringer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.EnumOptions.getDefaultInstance(),
        false,
        null,
        null,
        62022,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ENUM_CUSTOMNAME_FIELD_NUMBER = 62023;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.String> enumCustomname = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.EnumOptions.getDefaultInstance(),
        "",
        null,
        null,
        62023,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int ENUMDECL_FIELD_NUMBER = 62024;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Boolean> enumdecl = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.EnumOptions.getDefaultInstance(),
        false,
        null,
        null,
        62024,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ENUMVALUE_CUSTOMNAME_FIELD_NUMBER = 66001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> enumvalueCustomname = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.EnumValueOptions.getDefaultInstance(),
        "",
        null,
        null,
        66001,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int GOPROTO_GETTERS_ALL_FIELD_NUMBER = 63001;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoGettersAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63001,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_ENUM_PREFIX_ALL_FIELD_NUMBER = 63002;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoEnumPrefixAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63002,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_STRINGER_ALL_FIELD_NUMBER = 63003;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoStringerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63003,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int VERBOSE_EQUAL_ALL_FIELD_NUMBER = 63004;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> verboseEqualAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63004,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int FACE_ALL_FIELD_NUMBER = 63005;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> faceAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63005,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOSTRING_ALL_FIELD_NUMBER = 63006;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> gostringAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63006,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int POPULATE_ALL_FIELD_NUMBER = 63007;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> populateAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63007,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int STRINGER_ALL_FIELD_NUMBER = 63008;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> stringerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63008,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ONLYONE_ALL_FIELD_NUMBER = 63009;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> onlyoneAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63009,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int EQUAL_ALL_FIELD_NUMBER = 63013;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> equalAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63013,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int DESCRIPTION_ALL_FIELD_NUMBER = 63014;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> descriptionAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63014,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int TESTGEN_ALL_FIELD_NUMBER = 63015;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> testgenAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63015,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int BENCHGEN_ALL_FIELD_NUMBER = 63016;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> benchgenAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63016,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int MARSHALER_ALL_FIELD_NUMBER = 63017;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> marshalerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63017,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int UNMARSHALER_ALL_FIELD_NUMBER = 63018;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> unmarshalerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63018,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int STABLE_MARSHALER_ALL_FIELD_NUMBER = 63019;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> stableMarshalerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63019,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int SIZER_ALL_FIELD_NUMBER = 63020;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> sizerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63020,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_ENUM_STRINGER_ALL_FIELD_NUMBER = 63021;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoEnumStringerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63021,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ENUM_STRINGER_ALL_FIELD_NUMBER = 63022;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> enumStringerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63022,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int UNSAFE_MARSHALER_ALL_FIELD_NUMBER = 63023;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> unsafeMarshalerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63023,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int UNSAFE_UNMARSHALER_ALL_FIELD_NUMBER = 63024;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> unsafeUnmarshalerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63024,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_EXTENSIONS_MAP_ALL_FIELD_NUMBER = 63025;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoExtensionsMapAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63025,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_UNRECOGNIZED_ALL_FIELD_NUMBER = 63026;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoUnrecognizedAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63026,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOGOPROTO_IMPORT_FIELD_NUMBER = 63027;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> gogoprotoImport = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63027,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int PROTOSIZER_ALL_FIELD_NUMBER = 63028;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> protosizerAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63028,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int COMPARE_ALL_FIELD_NUMBER = 63029;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> compareAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63029,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int TYPEDECL_ALL_FIELD_NUMBER = 63030;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> typedeclAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63030,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ENUMDECL_ALL_FIELD_NUMBER = 63031;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> enumdeclAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63031,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_REGISTRATION_FIELD_NUMBER = 63032;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoRegistration = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63032,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int MESSAGENAME_ALL_FIELD_NUMBER = 63033;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> messagenameAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63033,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_SIZECACHE_ALL_FIELD_NUMBER = 63034;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoSizecacheAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63034,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_UNKEYED_ALL_FIELD_NUMBER = 63035;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.Boolean> goprotoUnkeyedAll = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FileOptions.getDefaultInstance(),
        false,
        null,
        null,
        63035,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_GETTERS_FIELD_NUMBER = 64001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoGetters = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64001,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_STRINGER_FIELD_NUMBER = 64003;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoStringer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64003,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int VERBOSE_EQUAL_FIELD_NUMBER = 64004;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> verboseEqual = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64004,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int FACE_FIELD_NUMBER = 64005;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> face = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64005,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOSTRING_FIELD_NUMBER = 64006;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> gostring = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64006,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int POPULATE_FIELD_NUMBER = 64007;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> populate = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64007,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int STRINGER_FIELD_NUMBER = 67008;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> stringer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        67008,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int ONLYONE_FIELD_NUMBER = 64009;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> onlyone = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64009,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int EQUAL_FIELD_NUMBER = 64013;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> equal = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64013,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int DESCRIPTION_FIELD_NUMBER = 64014;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> description = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64014,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int TESTGEN_FIELD_NUMBER = 64015;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> testgen = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64015,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int BENCHGEN_FIELD_NUMBER = 64016;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> benchgen = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64016,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int MARSHALER_FIELD_NUMBER = 64017;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> marshaler = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64017,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int UNMARSHALER_FIELD_NUMBER = 64018;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> unmarshaler = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64018,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int STABLE_MARSHALER_FIELD_NUMBER = 64019;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> stableMarshaler = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64019,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int SIZER_FIELD_NUMBER = 64020;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> sizer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64020,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int UNSAFE_MARSHALER_FIELD_NUMBER = 64023;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> unsafeMarshaler = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64023,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int UNSAFE_UNMARSHALER_FIELD_NUMBER = 64024;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> unsafeUnmarshaler = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64024,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_EXTENSIONS_MAP_FIELD_NUMBER = 64025;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoExtensionsMap = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64025,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_UNRECOGNIZED_FIELD_NUMBER = 64026;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoUnrecognized = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64026,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int PROTOSIZER_FIELD_NUMBER = 64028;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> protosizer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64028,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int COMPARE_FIELD_NUMBER = 64029;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> compare = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64029,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int TYPEDECL_FIELD_NUMBER = 64030;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> typedecl = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64030,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int MESSAGENAME_FIELD_NUMBER = 64033;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> messagename = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64033,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_SIZECACHE_FIELD_NUMBER = 64034;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoSizecache = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64034,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int GOPROTO_UNKEYED_FIELD_NUMBER = 64035;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> goprotoUnkeyed = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MessageOptions.getDefaultInstance(),
        false,
        null,
        null,
        64035,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int NULLABLE_FIELD_NUMBER = 65001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> nullable = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        false,
        null,
        null,
        65001,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int EMBED_FIELD_NUMBER = 65002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> embed = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        false,
        null,
        null,
        65002,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int CUSTOMTYPE_FIELD_NUMBER = 65003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> customtype = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65003,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int CUSTOMNAME_FIELD_NUMBER = 65004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> customname = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65004,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int JSONTAG_FIELD_NUMBER = 65005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> jsontag = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65005,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int MORETAGS_FIELD_NUMBER = 65006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> moretags = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65006,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int CASTTYPE_FIELD_NUMBER = 65007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> casttype = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65007,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int CASTKEY_FIELD_NUMBER = 65008;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> castkey = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65008,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int CASTVALUE_FIELD_NUMBER = 65009;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> castvalue = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65009,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);
  public static final int STDTIME_FIELD_NUMBER = 65010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> stdtime = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        false,
        null,
        null,
        65010,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int STDDURATION_FIELD_NUMBER = 65011;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> stdduration = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        false,
        null,
        null,
        65011,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int WKTPOINTER_FIELD_NUMBER = 65012;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> wktpointer = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        false,
        null,
        null,
        65012,
        com.google.protobuf.WireFormat.FieldType.BOOL,
        java.lang.Boolean.class);
  public static final int CASTREPEATED_FIELD_NUMBER = 65013;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> castrepeated = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
        "",
        null,
        null,
        65013,
        com.google.protobuf.WireFormat.FieldType.STRING,
        java.lang.String.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
