name: Label Checker
on:
  push:
    - "**"

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@v1.4.30         
        with:
          one_of: major,minor,patch
          any_of: documentation,enhancement,bug, cicd
          repo_token: ${{ secrets.GITHUB_TOKEN }}
