name: Check version-bump label
on:
  pull_request:
    branches:
      - "main"
    # paths:
    #   - ".github/workflows/labeler.yml"
    #   - ".github/labeler.yml"
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  require-version-bump-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "bump:patch, bump:minor, bump:major, bump:none"
