name: Build Proto Generated Go Library 

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'libraries/go/**'
  push:
    branches:
      - main
    paths:
      - 'libraries/go/**'

jobs:
  build:
    name: Go build
    runs-on: ubuntu-latest
    steps:
      # Clone
      - name: Checkout
        uses: actions/checkout@v3

      # Install and setup go
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      # setup gopath
      - name: Set PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      # proto 
      - name:  Make go proto 
        run: make proto-gen-go
      
      # build go library
      - name: Build go libraries
        run: make gobuild
