name: Pull Request Labeler 
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/labeler.yml"
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "PR Number is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: check pr pr-number
        run: echo ${{ github.event.number }}

      - uses: actions/labeler@v4
        with:
          dot: true
          pr-number: ${{ steps.findPr.outputs.pr }}