name: Pull Request Labeler 
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/labeler.yml"
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/labeler@v4
        with:
          dot: true
          pr-number: ${{ steps.pr.outputs.pull_request_number }}